# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1


jobs:
  build-and-test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/frontend
          cache-path: ~/project/frontend/node_modules
          override-ci-command: npm i
      - run:
          name: Run tests
          command: npm --prefix frontend/ test
      - run:
          name: Build Create React App
          command: npm --prefix frontend/ run build
      - persist_to_workspace:
          root: frontend
          paths:
            - build
            - node_modules

  deploy:  
    docker:
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Firebase Deploy
          command: cd /tmp/workspace && node_modules/.bin/firebase deploy --project "$FIREBASE_PROJECT_ID" --token "$FIREBASE_TOKEN"

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
        filters:
          braches:
            only: main
        requires:
          - build-and-test
